[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-autosuggestions"
  refreshPeriod = "168h"

[".vim/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"

[".config/foot/catppuccin-mocha.ini"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/foot/refs/heads/main/themes/catppuccin-mocha.ini"
  refreshPeriod = "168h"

[".config/btop/themes/catppuccin-mocha.theme"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/btop/refs/heads/main/themes/catppuccin_mocha.theme"
  refreshPeriod = "168h"

[".config/fuzzel/catppuccin-mocha-peach.ini"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/fuzzel/refs/heads/main/themes/catppuccin-mocha/peach.ini"
  refreshPeriod = "168h"
