[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-autosuggestions/archive/refs/heads/master.zip"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".vim/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"

[".config/foot/catppuccin-mocha.ini"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/foot/refs/heads/main/themes/catppuccin-mocha.ini"
  refreshPeriod = "168h"

[".config/btop/themes/catppuccin-mocha.theme"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/btop/refs/heads/main/themes/catppuccin_mocha.theme"
  refreshPeriod = "168h"

[".config/fuzzel/catppuccin-mocha-peach.ini"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/fuzzel/refs/heads/main/themes/catppuccin-mocha/peach.ini"
  refreshPeriod = "168h"

[".config/tmux/plugins/catppuccin/tmux"]
  type = "archive"
  url = "https://github.com/catppuccin/tmux/archive/refs/tags/v2.1.3.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

